language: node_js

node_js:
  - node

before_install:
  - git submodule update --init --recursive

install:
  - npm install

before_script:
  # - git clone -q git://github.com/n1k0/casperjs.git
  # - cd casperjs; git checkout -q tags/1.1-beta1; cd ../
  - export PATH=$PATH:`pwd`/casperjs/bin
  - npm install -g casperjs
  - phantomjs --version; casperjs --version

script: npm test
